### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Vlad756** [mocox/data-structs#4]
In my opinion menue links works not correct. You have to push exactly link text to switch page, can't we make a menue links like buttons or smth. I'll show you by screen sharing next time.

We can add a dark theme on a site.

The "Links" part of the site is too big. Can we make it smaller or move links to the menue component?

What do you think to move version of the site to the right side of the menue?

**Comment by mocox** [comment]
You will have to show me what you mean when we next have call about menus.

Lets check what dark theme looks like first. We should be able to let user choose theme really.

We can make the links section smaller but we can use the links column for other things like ads or something, should not be too hard to change but i think they should be there.

Yes move the version to the right. if you set the width of the nav ul to 100% it should go there.
